# Generated by Django 4.1.7 on 2023-04-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('apply_linkedIn', models.TextField(default='')),
                ('apply', models.TextField(default='')),
                ('discription', models.TextField()),
                ('company', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('company_linkedIn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LastRefreash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
